// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avim-base.proto

#ifndef PROTOBUF_avim_2dbase_2eproto__INCLUDED
#define PROTOBUF_avim_2dbase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace base {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_avim_2dbase_2eproto();
void protobuf_AssignDesc_avim_2dbase_2eproto();
void protobuf_ShutdownFile_avim_2dbase_2eproto();

class avAddress;
class avPacket;
class avPacket_ack_control;
class aGMP;
class aGMP_PKREPLY;
class aGMP_NOROUTTOHOST;
class aGMP_TTLOUT;
class avTCPPacket;

// ===================================================================

class avAddress : public ::google::protobuf::Message {
 public:
  avAddress();
  virtual ~avAddress();

  avAddress(const avAddress& from);

  inline avAddress& operator=(const avAddress& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const avAddress& default_instance();

  void Swap(avAddress* other);

  // implements Message ----------------------------------------------

  avAddress* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const avAddress& from);
  void MergeFrom(const avAddress& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string username = 1;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 1;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // required string domain = 2;
  inline bool has_domain() const;
  inline void clear_domain();
  static const int kDomainFieldNumber = 2;
  inline const ::std::string& domain() const;
  inline void set_domain(const ::std::string& value);
  inline void set_domain(const char* value);
  inline void set_domain(const char* value, size_t size);
  inline ::std::string* mutable_domain();
  inline ::std::string* release_domain();
  inline void set_allocated_domain(::std::string* domain);

  // optional string resource = 3;
  inline bool has_resource() const;
  inline void clear_resource();
  static const int kResourceFieldNumber = 3;
  inline const ::std::string& resource() const;
  inline void set_resource(const ::std::string& value);
  inline void set_resource(const char* value);
  inline void set_resource(const char* value, size_t size);
  inline ::std::string* mutable_resource();
  inline ::std::string* release_resource();
  inline void set_allocated_resource(::std::string* resource);

  // @@protoc_insertion_point(class_scope:proto.base.avAddress)
 private:
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_domain();
  inline void clear_has_domain();
  inline void set_has_resource();
  inline void clear_has_resource();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* username_;
  ::std::string* domain_;
  ::std::string* resource_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static avAddress* default_instance_;
};
// -------------------------------------------------------------------

class avPacket_ack_control : public ::google::protobuf::Message {
 public:
  avPacket_ack_control();
  virtual ~avPacket_ack_control();

  avPacket_ack_control(const avPacket_ack_control& from);

  inline avPacket_ack_control& operator=(const avPacket_ack_control& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const avPacket_ack_control& default_instance();

  void Swap(avPacket_ack_control* other);

  // implements Message ----------------------------------------------

  avPacket_ack_control* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const avPacket_ack_control& from);
  void MergeFrom(const avPacket_ack_control& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 ack_seq = 1;
  inline bool has_ack_seq() const;
  inline void clear_ack_seq();
  static const int kAckSeqFieldNumber = 1;
  inline ::google::protobuf::uint64 ack_seq() const;
  inline void set_ack_seq(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:proto.base.avPacket.ack_control)
 private:
  inline void set_has_ack_seq();
  inline void clear_has_ack_seq();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 ack_seq_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static avPacket_ack_control* default_instance_;
};
// -------------------------------------------------------------------

class avPacket : public ::google::protobuf::Message {
 public:
  avPacket();
  virtual ~avPacket();

  avPacket(const avPacket& from);

  inline avPacket& operator=(const avPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const avPacket& default_instance();

  void Swap(avPacket* other);

  // implements Message ----------------------------------------------

  avPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const avPacket& from);
  void MergeFrom(const avPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef avPacket_ack_control ack_control;

  // accessors -------------------------------------------------------

  // required .proto.base.avAddress src = 1;
  inline bool has_src() const;
  inline void clear_src();
  static const int kSrcFieldNumber = 1;
  inline const ::proto::base::avAddress& src() const;
  inline ::proto::base::avAddress* mutable_src();
  inline ::proto::base::avAddress* release_src();
  inline void set_allocated_src(::proto::base::avAddress* src);

  // required .proto.base.avAddress dest = 2;
  inline bool has_dest() const;
  inline void clear_dest();
  static const int kDestFieldNumber = 2;
  inline const ::proto::base::avAddress& dest() const;
  inline ::proto::base::avAddress* mutable_dest();
  inline ::proto::base::avAddress* release_dest();
  inline void set_allocated_dest(::proto::base::avAddress* dest);

  // optional bytes publickey = 3;
  inline bool has_publickey() const;
  inline void clear_publickey();
  static const int kPublickeyFieldNumber = 3;
  inline const ::std::string& publickey() const;
  inline void set_publickey(const ::std::string& value);
  inline void set_publickey(const char* value);
  inline void set_publickey(const void* value, size_t size);
  inline ::std::string* mutable_publickey();
  inline ::std::string* release_publickey();
  inline void set_allocated_publickey(::std::string* publickey);

  // required uint32 time_to_live = 4 [default = 64];
  inline bool has_time_to_live() const;
  inline void clear_time_to_live();
  static const int kTimeToLiveFieldNumber = 4;
  inline ::google::protobuf::uint32 time_to_live() const;
  inline void set_time_to_live(::google::protobuf::uint32 value);

  // required string upperlayerpotocol = 6 [default = "avim"];
  inline bool has_upperlayerpotocol() const;
  inline void clear_upperlayerpotocol();
  static const int kUpperlayerpotocolFieldNumber = 6;
  inline const ::std::string& upperlayerpotocol() const;
  inline void set_upperlayerpotocol(const ::std::string& value);
  inline void set_upperlayerpotocol(const char* value);
  inline void set_upperlayerpotocol(const char* value, size_t size);
  inline ::std::string* mutable_upperlayerpotocol();
  inline ::std::string* release_upperlayerpotocol();
  inline void set_allocated_upperlayerpotocol(::std::string* upperlayerpotocol);

  // optional uint32 encrype_method = 7 [default = 0];
  inline bool has_encrype_method() const;
  inline void clear_encrype_method();
  static const int kEncrypeMethodFieldNumber = 7;
  inline ::google::protobuf::uint32 encrype_method() const;
  inline void set_encrype_method(::google::protobuf::uint32 value);

  // optional bool msg_dont_route = 9;
  inline bool has_msg_dont_route() const;
  inline void clear_msg_dont_route();
  static const int kMsgDontRouteFieldNumber = 9;
  inline bool msg_dont_route() const;
  inline void set_msg_dont_route(bool value);

  // optional .proto.base.avPacket.ack_control need_seq = 11;
  inline bool has_need_seq() const;
  inline void clear_need_seq();
  static const int kNeedSeqFieldNumber = 11;
  inline const ::proto::base::avPacket_ack_control& need_seq() const;
  inline ::proto::base::avPacket_ack_control* mutable_need_seq();
  inline ::proto::base::avPacket_ack_control* release_need_seq();
  inline void set_allocated_need_seq(::proto::base::avPacket_ack_control* need_seq);

  // optional bytes payload = 8;
  inline bool has_payload() const;
  inline void clear_payload();
  static const int kPayloadFieldNumber = 8;
  inline const ::std::string& payload() const;
  inline void set_payload(const ::std::string& value);
  inline void set_payload(const char* value);
  inline void set_payload(const void* value, size_t size);
  inline ::std::string* mutable_payload();
  inline ::std::string* release_payload();
  inline void set_allocated_payload(::std::string* payload);

  // @@protoc_insertion_point(class_scope:proto.base.avPacket)
 private:
  inline void set_has_src();
  inline void clear_has_src();
  inline void set_has_dest();
  inline void clear_has_dest();
  inline void set_has_publickey();
  inline void clear_has_publickey();
  inline void set_has_time_to_live();
  inline void clear_has_time_to_live();
  inline void set_has_upperlayerpotocol();
  inline void clear_has_upperlayerpotocol();
  inline void set_has_encrype_method();
  inline void clear_has_encrype_method();
  inline void set_has_msg_dont_route();
  inline void clear_has_msg_dont_route();
  inline void set_has_need_seq();
  inline void clear_has_need_seq();
  inline void set_has_payload();
  inline void clear_has_payload();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::proto::base::avAddress* src_;
  ::proto::base::avAddress* dest_;
  ::std::string* publickey_;
  static ::std::string* _default_upperlayerpotocol_;
  ::std::string* upperlayerpotocol_;
  ::google::protobuf::uint32 time_to_live_;
  ::google::protobuf::uint32 encrype_method_;
  ::proto::base::avPacket_ack_control* need_seq_;
  ::std::string* payload_;
  bool msg_dont_route_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static avPacket* default_instance_;
};
// -------------------------------------------------------------------

class aGMP_PKREPLY : public ::google::protobuf::Message {
 public:
  aGMP_PKREPLY();
  virtual ~aGMP_PKREPLY();

  aGMP_PKREPLY(const aGMP_PKREPLY& from);

  inline aGMP_PKREPLY& operator=(const aGMP_PKREPLY& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const aGMP_PKREPLY& default_instance();

  void Swap(aGMP_PKREPLY* other);

  // implements Message ----------------------------------------------

  aGMP_PKREPLY* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const aGMP_PKREPLY& from);
  void MergeFrom(const aGMP_PKREPLY& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes x509_cert = 1;
  inline bool has_x509_cert() const;
  inline void clear_x509_cert();
  static const int kX509CertFieldNumber = 1;
  inline const ::std::string& x509_cert() const;
  inline void set_x509_cert(const ::std::string& value);
  inline void set_x509_cert(const char* value);
  inline void set_x509_cert(const void* value, size_t size);
  inline ::std::string* mutable_x509_cert();
  inline ::std::string* release_x509_cert();
  inline void set_allocated_x509_cert(::std::string* x509_cert);

  // @@protoc_insertion_point(class_scope:proto.base.aGMP.PKREPLY)
 private:
  inline void set_has_x509_cert();
  inline void clear_has_x509_cert();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* x509_cert_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static aGMP_PKREPLY* default_instance_;
};
// -------------------------------------------------------------------

class aGMP_NOROUTTOHOST : public ::google::protobuf::Message {
 public:
  aGMP_NOROUTTOHOST();
  virtual ~aGMP_NOROUTTOHOST();

  aGMP_NOROUTTOHOST(const aGMP_NOROUTTOHOST& from);

  inline aGMP_NOROUTTOHOST& operator=(const aGMP_NOROUTTOHOST& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const aGMP_NOROUTTOHOST& default_instance();

  void Swap(aGMP_NOROUTTOHOST* other);

  // implements Message ----------------------------------------------

  aGMP_NOROUTTOHOST* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const aGMP_NOROUTTOHOST& from);
  void MergeFrom(const aGMP_NOROUTTOHOST& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .proto.base.avAddress host = 1;
  inline bool has_host() const;
  inline void clear_host();
  static const int kHostFieldNumber = 1;
  inline const ::proto::base::avAddress& host() const;
  inline ::proto::base::avAddress* mutable_host();
  inline ::proto::base::avAddress* release_host();
  inline void set_allocated_host(::proto::base::avAddress* host);

  // @@protoc_insertion_point(class_scope:proto.base.aGMP.NOROUTTOHOST)
 private:
  inline void set_has_host();
  inline void clear_has_host();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::proto::base::avAddress* host_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static aGMP_NOROUTTOHOST* default_instance_;
};
// -------------------------------------------------------------------

class aGMP_TTLOUT : public ::google::protobuf::Message {
 public:
  aGMP_TTLOUT();
  virtual ~aGMP_TTLOUT();

  aGMP_TTLOUT(const aGMP_TTLOUT& from);

  inline aGMP_TTLOUT& operator=(const aGMP_TTLOUT& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const aGMP_TTLOUT& default_instance();

  void Swap(aGMP_TTLOUT* other);

  // implements Message ----------------------------------------------

  aGMP_TTLOUT* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const aGMP_TTLOUT& from);
  void MergeFrom(const aGMP_TTLOUT& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .proto.base.avAddress host = 1;
  inline bool has_host() const;
  inline void clear_host();
  static const int kHostFieldNumber = 1;
  inline const ::proto::base::avAddress& host() const;
  inline ::proto::base::avAddress* mutable_host();
  inline ::proto::base::avAddress* release_host();
  inline void set_allocated_host(::proto::base::avAddress* host);

  // @@protoc_insertion_point(class_scope:proto.base.aGMP.TTLOUT)
 private:
  inline void set_has_host();
  inline void clear_has_host();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::proto::base::avAddress* host_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static aGMP_TTLOUT* default_instance_;
};
// -------------------------------------------------------------------

class aGMP : public ::google::protobuf::Message {
 public:
  aGMP();
  virtual ~aGMP();

  aGMP(const aGMP& from);

  inline aGMP& operator=(const aGMP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const aGMP& default_instance();

  void Swap(aGMP* other);

  // implements Message ----------------------------------------------

  aGMP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const aGMP& from);
  void MergeFrom(const aGMP& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef aGMP_PKREPLY PKREPLY;
  typedef aGMP_NOROUTTOHOST NOROUTTOHOST;
  typedef aGMP_TTLOUT TTLOUT;

  // accessors -------------------------------------------------------

  // optional .proto.base.aGMP.PKREPLY pkreply = 1;
  inline bool has_pkreply() const;
  inline void clear_pkreply();
  static const int kPkreplyFieldNumber = 1;
  inline const ::proto::base::aGMP_PKREPLY& pkreply() const;
  inline ::proto::base::aGMP_PKREPLY* mutable_pkreply();
  inline ::proto::base::aGMP_PKREPLY* release_pkreply();
  inline void set_allocated_pkreply(::proto::base::aGMP_PKREPLY* pkreply);

  // optional .proto.base.aGMP.NOROUTTOHOST noroutetohost = 2;
  inline bool has_noroutetohost() const;
  inline void clear_noroutetohost();
  static const int kNoroutetohostFieldNumber = 2;
  inline const ::proto::base::aGMP_NOROUTTOHOST& noroutetohost() const;
  inline ::proto::base::aGMP_NOROUTTOHOST* mutable_noroutetohost();
  inline ::proto::base::aGMP_NOROUTTOHOST* release_noroutetohost();
  inline void set_allocated_noroutetohost(::proto::base::aGMP_NOROUTTOHOST* noroutetohost);

  // optional .proto.base.aGMP.TTLOUT ttlout = 3;
  inline bool has_ttlout() const;
  inline void clear_ttlout();
  static const int kTtloutFieldNumber = 3;
  inline const ::proto::base::aGMP_TTLOUT& ttlout() const;
  inline ::proto::base::aGMP_TTLOUT* mutable_ttlout();
  inline ::proto::base::aGMP_TTLOUT* release_ttlout();
  inline void set_allocated_ttlout(::proto::base::aGMP_TTLOUT* ttlout);

  // @@protoc_insertion_point(class_scope:proto.base.aGMP)
 private:
  inline void set_has_pkreply();
  inline void clear_has_pkreply();
  inline void set_has_noroutetohost();
  inline void clear_has_noroutetohost();
  inline void set_has_ttlout();
  inline void clear_has_ttlout();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::proto::base::aGMP_PKREPLY* pkreply_;
  ::proto::base::aGMP_NOROUTTOHOST* noroutetohost_;
  ::proto::base::aGMP_TTLOUT* ttlout_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static aGMP* default_instance_;
};
// -------------------------------------------------------------------

class avTCPPacket : public ::google::protobuf::Message {
 public:
  avTCPPacket();
  virtual ~avTCPPacket();

  avTCPPacket(const avTCPPacket& from);

  inline avTCPPacket& operator=(const avTCPPacket& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const avTCPPacket& default_instance();

  void Swap(avTCPPacket* other);

  // implements Message ----------------------------------------------

  avTCPPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const avTCPPacket& from);
  void MergeFrom(const avTCPPacket& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional .proto.base.avPacket avpacket = 2;
  inline bool has_avpacket() const;
  inline void clear_avpacket();
  static const int kAvpacketFieldNumber = 2;
  inline const ::proto::base::avPacket& avpacket() const;
  inline ::proto::base::avPacket* mutable_avpacket();
  inline ::proto::base::avPacket* release_avpacket();
  inline void set_allocated_avpacket(::proto::base::avPacket* avpacket);

  // optional .proto.base.avAddress endpoint_address = 3;
  inline bool has_endpoint_address() const;
  inline void clear_endpoint_address();
  static const int kEndpointAddressFieldNumber = 3;
  inline const ::proto::base::avAddress& endpoint_address() const;
  inline ::proto::base::avAddress* mutable_endpoint_address();
  inline ::proto::base::avAddress* release_endpoint_address();
  inline void set_allocated_endpoint_address(::proto::base::avAddress* endpoint_address);

  // optional bytes endpoint_cert = 4;
  inline bool has_endpoint_cert() const;
  inline void clear_endpoint_cert();
  static const int kEndpointCertFieldNumber = 4;
  inline const ::std::string& endpoint_cert() const;
  inline void set_endpoint_cert(const ::std::string& value);
  inline void set_endpoint_cert(const char* value);
  inline void set_endpoint_cert(const void* value, size_t size);
  inline ::std::string* mutable_endpoint_cert();
  inline ::std::string* release_endpoint_cert();
  inline void set_allocated_endpoint_cert(::std::string* endpoint_cert);

  // @@protoc_insertion_point(class_scope:proto.base.avTCPPacket)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_avpacket();
  inline void clear_has_avpacket();
  inline void set_has_endpoint_address();
  inline void clear_has_endpoint_address();
  inline void set_has_endpoint_cert();
  inline void clear_has_endpoint_cert();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::proto::base::avPacket* avpacket_;
  ::proto::base::avAddress* endpoint_address_;
  ::std::string* endpoint_cert_;
  ::google::protobuf::uint32 type_;
  friend void  protobuf_AddDesc_avim_2dbase_2eproto();
  friend void protobuf_AssignDesc_avim_2dbase_2eproto();
  friend void protobuf_ShutdownFile_avim_2dbase_2eproto();

  void InitAsDefaultInstance();
  static avTCPPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// avAddress

// required string username = 1;
inline bool avAddress::has_username() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void avAddress::set_has_username() {
  _has_bits_[0] |= 0x00000001u;
}
inline void avAddress::clear_has_username() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void avAddress::clear_username() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& avAddress::username() const {
  // @@protoc_insertion_point(field_get:proto.base.avAddress.username)
  return *username_;
}
inline void avAddress::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avAddress.username)
}
inline void avAddress::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avAddress.username)
}
inline void avAddress::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avAddress.username)
}
inline ::std::string* avAddress::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avAddress.username)
  return username_;
}
inline ::std::string* avAddress::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void avAddress::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avAddress.username)
}

// required string domain = 2;
inline bool avAddress::has_domain() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void avAddress::set_has_domain() {
  _has_bits_[0] |= 0x00000002u;
}
inline void avAddress::clear_has_domain() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void avAddress::clear_domain() {
  if (domain_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_->clear();
  }
  clear_has_domain();
}
inline const ::std::string& avAddress::domain() const {
  // @@protoc_insertion_point(field_get:proto.base.avAddress.domain)
  return *domain_;
}
inline void avAddress::set_domain(const ::std::string& value) {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  domain_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avAddress.domain)
}
inline void avAddress::set_domain(const char* value) {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  domain_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avAddress.domain)
}
inline void avAddress::set_domain(const char* value, size_t size) {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  domain_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avAddress.domain)
}
inline ::std::string* avAddress::mutable_domain() {
  set_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    domain_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avAddress.domain)
  return domain_;
}
inline ::std::string* avAddress::release_domain() {
  clear_has_domain();
  if (domain_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = domain_;
    domain_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void avAddress::set_allocated_domain(::std::string* domain) {
  if (domain_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete domain_;
  }
  if (domain) {
    set_has_domain();
    domain_ = domain;
  } else {
    clear_has_domain();
    domain_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avAddress.domain)
}

// optional string resource = 3;
inline bool avAddress::has_resource() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void avAddress::set_has_resource() {
  _has_bits_[0] |= 0x00000004u;
}
inline void avAddress::clear_has_resource() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void avAddress::clear_resource() {
  if (resource_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_->clear();
  }
  clear_has_resource();
}
inline const ::std::string& avAddress::resource() const {
  // @@protoc_insertion_point(field_get:proto.base.avAddress.resource)
  return *resource_;
}
inline void avAddress::set_resource(const ::std::string& value) {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  resource_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avAddress.resource)
}
inline void avAddress::set_resource(const char* value) {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  resource_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avAddress.resource)
}
inline void avAddress::set_resource(const char* value, size_t size) {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  resource_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avAddress.resource)
}
inline ::std::string* avAddress::mutable_resource() {
  set_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    resource_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avAddress.resource)
  return resource_;
}
inline ::std::string* avAddress::release_resource() {
  clear_has_resource();
  if (resource_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = resource_;
    resource_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void avAddress::set_allocated_resource(::std::string* resource) {
  if (resource_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete resource_;
  }
  if (resource) {
    set_has_resource();
    resource_ = resource;
  } else {
    clear_has_resource();
    resource_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avAddress.resource)
}

// -------------------------------------------------------------------

// avPacket_ack_control

// required uint64 ack_seq = 1;
inline bool avPacket_ack_control::has_ack_seq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void avPacket_ack_control::set_has_ack_seq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void avPacket_ack_control::clear_has_ack_seq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void avPacket_ack_control::clear_ack_seq() {
  ack_seq_ = GOOGLE_ULONGLONG(0);
  clear_has_ack_seq();
}
inline ::google::protobuf::uint64 avPacket_ack_control::ack_seq() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.ack_control.ack_seq)
  return ack_seq_;
}
inline void avPacket_ack_control::set_ack_seq(::google::protobuf::uint64 value) {
  set_has_ack_seq();
  ack_seq_ = value;
  // @@protoc_insertion_point(field_set:proto.base.avPacket.ack_control.ack_seq)
}

// -------------------------------------------------------------------

// avPacket

// required .proto.base.avAddress src = 1;
inline bool avPacket::has_src() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void avPacket::set_has_src() {
  _has_bits_[0] |= 0x00000001u;
}
inline void avPacket::clear_has_src() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void avPacket::clear_src() {
  if (src_ != NULL) src_->::proto::base::avAddress::Clear();
  clear_has_src();
}
inline const ::proto::base::avAddress& avPacket::src() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.src)
  return src_ != NULL ? *src_ : *default_instance_->src_;
}
inline ::proto::base::avAddress* avPacket::mutable_src() {
  set_has_src();
  if (src_ == NULL) src_ = new ::proto::base::avAddress;
  // @@protoc_insertion_point(field_mutable:proto.base.avPacket.src)
  return src_;
}
inline ::proto::base::avAddress* avPacket::release_src() {
  clear_has_src();
  ::proto::base::avAddress* temp = src_;
  src_ = NULL;
  return temp;
}
inline void avPacket::set_allocated_src(::proto::base::avAddress* src) {
  delete src_;
  src_ = src;
  if (src) {
    set_has_src();
  } else {
    clear_has_src();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avPacket.src)
}

// required .proto.base.avAddress dest = 2;
inline bool avPacket::has_dest() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void avPacket::set_has_dest() {
  _has_bits_[0] |= 0x00000002u;
}
inline void avPacket::clear_has_dest() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void avPacket::clear_dest() {
  if (dest_ != NULL) dest_->::proto::base::avAddress::Clear();
  clear_has_dest();
}
inline const ::proto::base::avAddress& avPacket::dest() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.dest)
  return dest_ != NULL ? *dest_ : *default_instance_->dest_;
}
inline ::proto::base::avAddress* avPacket::mutable_dest() {
  set_has_dest();
  if (dest_ == NULL) dest_ = new ::proto::base::avAddress;
  // @@protoc_insertion_point(field_mutable:proto.base.avPacket.dest)
  return dest_;
}
inline ::proto::base::avAddress* avPacket::release_dest() {
  clear_has_dest();
  ::proto::base::avAddress* temp = dest_;
  dest_ = NULL;
  return temp;
}
inline void avPacket::set_allocated_dest(::proto::base::avAddress* dest) {
  delete dest_;
  dest_ = dest;
  if (dest) {
    set_has_dest();
  } else {
    clear_has_dest();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avPacket.dest)
}

// optional bytes publickey = 3;
inline bool avPacket::has_publickey() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void avPacket::set_has_publickey() {
  _has_bits_[0] |= 0x00000004u;
}
inline void avPacket::clear_has_publickey() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void avPacket::clear_publickey() {
  if (publickey_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    publickey_->clear();
  }
  clear_has_publickey();
}
inline const ::std::string& avPacket::publickey() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.publickey)
  return *publickey_;
}
inline void avPacket::set_publickey(const ::std::string& value) {
  set_has_publickey();
  if (publickey_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    publickey_ = new ::std::string;
  }
  publickey_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avPacket.publickey)
}
inline void avPacket::set_publickey(const char* value) {
  set_has_publickey();
  if (publickey_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    publickey_ = new ::std::string;
  }
  publickey_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avPacket.publickey)
}
inline void avPacket::set_publickey(const void* value, size_t size) {
  set_has_publickey();
  if (publickey_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    publickey_ = new ::std::string;
  }
  publickey_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avPacket.publickey)
}
inline ::std::string* avPacket::mutable_publickey() {
  set_has_publickey();
  if (publickey_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    publickey_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avPacket.publickey)
  return publickey_;
}
inline ::std::string* avPacket::release_publickey() {
  clear_has_publickey();
  if (publickey_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = publickey_;
    publickey_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void avPacket::set_allocated_publickey(::std::string* publickey) {
  if (publickey_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete publickey_;
  }
  if (publickey) {
    set_has_publickey();
    publickey_ = publickey;
  } else {
    clear_has_publickey();
    publickey_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avPacket.publickey)
}

// required uint32 time_to_live = 4 [default = 64];
inline bool avPacket::has_time_to_live() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void avPacket::set_has_time_to_live() {
  _has_bits_[0] |= 0x00000008u;
}
inline void avPacket::clear_has_time_to_live() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void avPacket::clear_time_to_live() {
  time_to_live_ = 64u;
  clear_has_time_to_live();
}
inline ::google::protobuf::uint32 avPacket::time_to_live() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.time_to_live)
  return time_to_live_;
}
inline void avPacket::set_time_to_live(::google::protobuf::uint32 value) {
  set_has_time_to_live();
  time_to_live_ = value;
  // @@protoc_insertion_point(field_set:proto.base.avPacket.time_to_live)
}

// required string upperlayerpotocol = 6 [default = "avim"];
inline bool avPacket::has_upperlayerpotocol() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void avPacket::set_has_upperlayerpotocol() {
  _has_bits_[0] |= 0x00000010u;
}
inline void avPacket::clear_has_upperlayerpotocol() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void avPacket::clear_upperlayerpotocol() {
  if (upperlayerpotocol_ != _default_upperlayerpotocol_) {
    upperlayerpotocol_->assign(*_default_upperlayerpotocol_);
  }
  clear_has_upperlayerpotocol();
}
inline const ::std::string& avPacket::upperlayerpotocol() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.upperlayerpotocol)
  return *upperlayerpotocol_;
}
inline void avPacket::set_upperlayerpotocol(const ::std::string& value) {
  set_has_upperlayerpotocol();
  if (upperlayerpotocol_ == _default_upperlayerpotocol_) {
    upperlayerpotocol_ = new ::std::string;
  }
  upperlayerpotocol_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avPacket.upperlayerpotocol)
}
inline void avPacket::set_upperlayerpotocol(const char* value) {
  set_has_upperlayerpotocol();
  if (upperlayerpotocol_ == _default_upperlayerpotocol_) {
    upperlayerpotocol_ = new ::std::string;
  }
  upperlayerpotocol_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avPacket.upperlayerpotocol)
}
inline void avPacket::set_upperlayerpotocol(const char* value, size_t size) {
  set_has_upperlayerpotocol();
  if (upperlayerpotocol_ == _default_upperlayerpotocol_) {
    upperlayerpotocol_ = new ::std::string;
  }
  upperlayerpotocol_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avPacket.upperlayerpotocol)
}
inline ::std::string* avPacket::mutable_upperlayerpotocol() {
  set_has_upperlayerpotocol();
  if (upperlayerpotocol_ == _default_upperlayerpotocol_) {
    upperlayerpotocol_ = new ::std::string(*_default_upperlayerpotocol_);
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avPacket.upperlayerpotocol)
  return upperlayerpotocol_;
}
inline ::std::string* avPacket::release_upperlayerpotocol() {
  clear_has_upperlayerpotocol();
  if (upperlayerpotocol_ == _default_upperlayerpotocol_) {
    return NULL;
  } else {
    ::std::string* temp = upperlayerpotocol_;
    upperlayerpotocol_ = const_cast< ::std::string*>(_default_upperlayerpotocol_);
    return temp;
  }
}
inline void avPacket::set_allocated_upperlayerpotocol(::std::string* upperlayerpotocol) {
  if (upperlayerpotocol_ != _default_upperlayerpotocol_) {
    delete upperlayerpotocol_;
  }
  if (upperlayerpotocol) {
    set_has_upperlayerpotocol();
    upperlayerpotocol_ = upperlayerpotocol;
  } else {
    clear_has_upperlayerpotocol();
    upperlayerpotocol_ = const_cast< ::std::string*>(_default_upperlayerpotocol_);
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avPacket.upperlayerpotocol)
}

// optional uint32 encrype_method = 7 [default = 0];
inline bool avPacket::has_encrype_method() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void avPacket::set_has_encrype_method() {
  _has_bits_[0] |= 0x00000020u;
}
inline void avPacket::clear_has_encrype_method() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void avPacket::clear_encrype_method() {
  encrype_method_ = 0u;
  clear_has_encrype_method();
}
inline ::google::protobuf::uint32 avPacket::encrype_method() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.encrype_method)
  return encrype_method_;
}
inline void avPacket::set_encrype_method(::google::protobuf::uint32 value) {
  set_has_encrype_method();
  encrype_method_ = value;
  // @@protoc_insertion_point(field_set:proto.base.avPacket.encrype_method)
}

// optional bool msg_dont_route = 9;
inline bool avPacket::has_msg_dont_route() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void avPacket::set_has_msg_dont_route() {
  _has_bits_[0] |= 0x00000040u;
}
inline void avPacket::clear_has_msg_dont_route() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void avPacket::clear_msg_dont_route() {
  msg_dont_route_ = false;
  clear_has_msg_dont_route();
}
inline bool avPacket::msg_dont_route() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.msg_dont_route)
  return msg_dont_route_;
}
inline void avPacket::set_msg_dont_route(bool value) {
  set_has_msg_dont_route();
  msg_dont_route_ = value;
  // @@protoc_insertion_point(field_set:proto.base.avPacket.msg_dont_route)
}

// optional .proto.base.avPacket.ack_control need_seq = 11;
inline bool avPacket::has_need_seq() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void avPacket::set_has_need_seq() {
  _has_bits_[0] |= 0x00000080u;
}
inline void avPacket::clear_has_need_seq() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void avPacket::clear_need_seq() {
  if (need_seq_ != NULL) need_seq_->::proto::base::avPacket_ack_control::Clear();
  clear_has_need_seq();
}
inline const ::proto::base::avPacket_ack_control& avPacket::need_seq() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.need_seq)
  return need_seq_ != NULL ? *need_seq_ : *default_instance_->need_seq_;
}
inline ::proto::base::avPacket_ack_control* avPacket::mutable_need_seq() {
  set_has_need_seq();
  if (need_seq_ == NULL) need_seq_ = new ::proto::base::avPacket_ack_control;
  // @@protoc_insertion_point(field_mutable:proto.base.avPacket.need_seq)
  return need_seq_;
}
inline ::proto::base::avPacket_ack_control* avPacket::release_need_seq() {
  clear_has_need_seq();
  ::proto::base::avPacket_ack_control* temp = need_seq_;
  need_seq_ = NULL;
  return temp;
}
inline void avPacket::set_allocated_need_seq(::proto::base::avPacket_ack_control* need_seq) {
  delete need_seq_;
  need_seq_ = need_seq;
  if (need_seq) {
    set_has_need_seq();
  } else {
    clear_has_need_seq();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avPacket.need_seq)
}

// optional bytes payload = 8;
inline bool avPacket::has_payload() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void avPacket::set_has_payload() {
  _has_bits_[0] |= 0x00000100u;
}
inline void avPacket::clear_has_payload() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void avPacket::clear_payload() {
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_->clear();
  }
  clear_has_payload();
}
inline const ::std::string& avPacket::payload() const {
  // @@protoc_insertion_point(field_get:proto.base.avPacket.payload)
  return *payload_;
}
inline void avPacket::set_payload(const ::std::string& value) {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  payload_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avPacket.payload)
}
inline void avPacket::set_payload(const char* value) {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  payload_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avPacket.payload)
}
inline void avPacket::set_payload(const void* value, size_t size) {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  payload_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avPacket.payload)
}
inline ::std::string* avPacket::mutable_payload() {
  set_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    payload_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avPacket.payload)
  return payload_;
}
inline ::std::string* avPacket::release_payload() {
  clear_has_payload();
  if (payload_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = payload_;
    payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void avPacket::set_allocated_payload(::std::string* payload) {
  if (payload_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete payload_;
  }
  if (payload) {
    set_has_payload();
    payload_ = payload;
  } else {
    clear_has_payload();
    payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avPacket.payload)
}

// -------------------------------------------------------------------

// aGMP_PKREPLY

// required bytes x509_cert = 1;
inline bool aGMP_PKREPLY::has_x509_cert() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void aGMP_PKREPLY::set_has_x509_cert() {
  _has_bits_[0] |= 0x00000001u;
}
inline void aGMP_PKREPLY::clear_has_x509_cert() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void aGMP_PKREPLY::clear_x509_cert() {
  if (x509_cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    x509_cert_->clear();
  }
  clear_has_x509_cert();
}
inline const ::std::string& aGMP_PKREPLY::x509_cert() const {
  // @@protoc_insertion_point(field_get:proto.base.aGMP.PKREPLY.x509_cert)
  return *x509_cert_;
}
inline void aGMP_PKREPLY::set_x509_cert(const ::std::string& value) {
  set_has_x509_cert();
  if (x509_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    x509_cert_ = new ::std::string;
  }
  x509_cert_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.aGMP.PKREPLY.x509_cert)
}
inline void aGMP_PKREPLY::set_x509_cert(const char* value) {
  set_has_x509_cert();
  if (x509_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    x509_cert_ = new ::std::string;
  }
  x509_cert_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.aGMP.PKREPLY.x509_cert)
}
inline void aGMP_PKREPLY::set_x509_cert(const void* value, size_t size) {
  set_has_x509_cert();
  if (x509_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    x509_cert_ = new ::std::string;
  }
  x509_cert_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.aGMP.PKREPLY.x509_cert)
}
inline ::std::string* aGMP_PKREPLY::mutable_x509_cert() {
  set_has_x509_cert();
  if (x509_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    x509_cert_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.aGMP.PKREPLY.x509_cert)
  return x509_cert_;
}
inline ::std::string* aGMP_PKREPLY::release_x509_cert() {
  clear_has_x509_cert();
  if (x509_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = x509_cert_;
    x509_cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void aGMP_PKREPLY::set_allocated_x509_cert(::std::string* x509_cert) {
  if (x509_cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete x509_cert_;
  }
  if (x509_cert) {
    set_has_x509_cert();
    x509_cert_ = x509_cert;
  } else {
    clear_has_x509_cert();
    x509_cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.aGMP.PKREPLY.x509_cert)
}

// -------------------------------------------------------------------

// aGMP_NOROUTTOHOST

// required .proto.base.avAddress host = 1;
inline bool aGMP_NOROUTTOHOST::has_host() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void aGMP_NOROUTTOHOST::set_has_host() {
  _has_bits_[0] |= 0x00000001u;
}
inline void aGMP_NOROUTTOHOST::clear_has_host() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void aGMP_NOROUTTOHOST::clear_host() {
  if (host_ != NULL) host_->::proto::base::avAddress::Clear();
  clear_has_host();
}
inline const ::proto::base::avAddress& aGMP_NOROUTTOHOST::host() const {
  // @@protoc_insertion_point(field_get:proto.base.aGMP.NOROUTTOHOST.host)
  return host_ != NULL ? *host_ : *default_instance_->host_;
}
inline ::proto::base::avAddress* aGMP_NOROUTTOHOST::mutable_host() {
  set_has_host();
  if (host_ == NULL) host_ = new ::proto::base::avAddress;
  // @@protoc_insertion_point(field_mutable:proto.base.aGMP.NOROUTTOHOST.host)
  return host_;
}
inline ::proto::base::avAddress* aGMP_NOROUTTOHOST::release_host() {
  clear_has_host();
  ::proto::base::avAddress* temp = host_;
  host_ = NULL;
  return temp;
}
inline void aGMP_NOROUTTOHOST::set_allocated_host(::proto::base::avAddress* host) {
  delete host_;
  host_ = host;
  if (host) {
    set_has_host();
  } else {
    clear_has_host();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.aGMP.NOROUTTOHOST.host)
}

// -------------------------------------------------------------------

// aGMP_TTLOUT

// required .proto.base.avAddress host = 1;
inline bool aGMP_TTLOUT::has_host() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void aGMP_TTLOUT::set_has_host() {
  _has_bits_[0] |= 0x00000001u;
}
inline void aGMP_TTLOUT::clear_has_host() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void aGMP_TTLOUT::clear_host() {
  if (host_ != NULL) host_->::proto::base::avAddress::Clear();
  clear_has_host();
}
inline const ::proto::base::avAddress& aGMP_TTLOUT::host() const {
  // @@protoc_insertion_point(field_get:proto.base.aGMP.TTLOUT.host)
  return host_ != NULL ? *host_ : *default_instance_->host_;
}
inline ::proto::base::avAddress* aGMP_TTLOUT::mutable_host() {
  set_has_host();
  if (host_ == NULL) host_ = new ::proto::base::avAddress;
  // @@protoc_insertion_point(field_mutable:proto.base.aGMP.TTLOUT.host)
  return host_;
}
inline ::proto::base::avAddress* aGMP_TTLOUT::release_host() {
  clear_has_host();
  ::proto::base::avAddress* temp = host_;
  host_ = NULL;
  return temp;
}
inline void aGMP_TTLOUT::set_allocated_host(::proto::base::avAddress* host) {
  delete host_;
  host_ = host;
  if (host) {
    set_has_host();
  } else {
    clear_has_host();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.aGMP.TTLOUT.host)
}

// -------------------------------------------------------------------

// aGMP

// optional .proto.base.aGMP.PKREPLY pkreply = 1;
inline bool aGMP::has_pkreply() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void aGMP::set_has_pkreply() {
  _has_bits_[0] |= 0x00000001u;
}
inline void aGMP::clear_has_pkreply() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void aGMP::clear_pkreply() {
  if (pkreply_ != NULL) pkreply_->::proto::base::aGMP_PKREPLY::Clear();
  clear_has_pkreply();
}
inline const ::proto::base::aGMP_PKREPLY& aGMP::pkreply() const {
  // @@protoc_insertion_point(field_get:proto.base.aGMP.pkreply)
  return pkreply_ != NULL ? *pkreply_ : *default_instance_->pkreply_;
}
inline ::proto::base::aGMP_PKREPLY* aGMP::mutable_pkreply() {
  set_has_pkreply();
  if (pkreply_ == NULL) pkreply_ = new ::proto::base::aGMP_PKREPLY;
  // @@protoc_insertion_point(field_mutable:proto.base.aGMP.pkreply)
  return pkreply_;
}
inline ::proto::base::aGMP_PKREPLY* aGMP::release_pkreply() {
  clear_has_pkreply();
  ::proto::base::aGMP_PKREPLY* temp = pkreply_;
  pkreply_ = NULL;
  return temp;
}
inline void aGMP::set_allocated_pkreply(::proto::base::aGMP_PKREPLY* pkreply) {
  delete pkreply_;
  pkreply_ = pkreply;
  if (pkreply) {
    set_has_pkreply();
  } else {
    clear_has_pkreply();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.aGMP.pkreply)
}

// optional .proto.base.aGMP.NOROUTTOHOST noroutetohost = 2;
inline bool aGMP::has_noroutetohost() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void aGMP::set_has_noroutetohost() {
  _has_bits_[0] |= 0x00000002u;
}
inline void aGMP::clear_has_noroutetohost() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void aGMP::clear_noroutetohost() {
  if (noroutetohost_ != NULL) noroutetohost_->::proto::base::aGMP_NOROUTTOHOST::Clear();
  clear_has_noroutetohost();
}
inline const ::proto::base::aGMP_NOROUTTOHOST& aGMP::noroutetohost() const {
  // @@protoc_insertion_point(field_get:proto.base.aGMP.noroutetohost)
  return noroutetohost_ != NULL ? *noroutetohost_ : *default_instance_->noroutetohost_;
}
inline ::proto::base::aGMP_NOROUTTOHOST* aGMP::mutable_noroutetohost() {
  set_has_noroutetohost();
  if (noroutetohost_ == NULL) noroutetohost_ = new ::proto::base::aGMP_NOROUTTOHOST;
  // @@protoc_insertion_point(field_mutable:proto.base.aGMP.noroutetohost)
  return noroutetohost_;
}
inline ::proto::base::aGMP_NOROUTTOHOST* aGMP::release_noroutetohost() {
  clear_has_noroutetohost();
  ::proto::base::aGMP_NOROUTTOHOST* temp = noroutetohost_;
  noroutetohost_ = NULL;
  return temp;
}
inline void aGMP::set_allocated_noroutetohost(::proto::base::aGMP_NOROUTTOHOST* noroutetohost) {
  delete noroutetohost_;
  noroutetohost_ = noroutetohost;
  if (noroutetohost) {
    set_has_noroutetohost();
  } else {
    clear_has_noroutetohost();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.aGMP.noroutetohost)
}

// optional .proto.base.aGMP.TTLOUT ttlout = 3;
inline bool aGMP::has_ttlout() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void aGMP::set_has_ttlout() {
  _has_bits_[0] |= 0x00000004u;
}
inline void aGMP::clear_has_ttlout() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void aGMP::clear_ttlout() {
  if (ttlout_ != NULL) ttlout_->::proto::base::aGMP_TTLOUT::Clear();
  clear_has_ttlout();
}
inline const ::proto::base::aGMP_TTLOUT& aGMP::ttlout() const {
  // @@protoc_insertion_point(field_get:proto.base.aGMP.ttlout)
  return ttlout_ != NULL ? *ttlout_ : *default_instance_->ttlout_;
}
inline ::proto::base::aGMP_TTLOUT* aGMP::mutable_ttlout() {
  set_has_ttlout();
  if (ttlout_ == NULL) ttlout_ = new ::proto::base::aGMP_TTLOUT;
  // @@protoc_insertion_point(field_mutable:proto.base.aGMP.ttlout)
  return ttlout_;
}
inline ::proto::base::aGMP_TTLOUT* aGMP::release_ttlout() {
  clear_has_ttlout();
  ::proto::base::aGMP_TTLOUT* temp = ttlout_;
  ttlout_ = NULL;
  return temp;
}
inline void aGMP::set_allocated_ttlout(::proto::base::aGMP_TTLOUT* ttlout) {
  delete ttlout_;
  ttlout_ = ttlout;
  if (ttlout) {
    set_has_ttlout();
  } else {
    clear_has_ttlout();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.aGMP.ttlout)
}

// -------------------------------------------------------------------

// avTCPPacket

// required uint32 type = 1;
inline bool avTCPPacket::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void avTCPPacket::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void avTCPPacket::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void avTCPPacket::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 avTCPPacket::type() const {
  // @@protoc_insertion_point(field_get:proto.base.avTCPPacket.type)
  return type_;
}
inline void avTCPPacket::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:proto.base.avTCPPacket.type)
}

// optional .proto.base.avPacket avpacket = 2;
inline bool avTCPPacket::has_avpacket() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void avTCPPacket::set_has_avpacket() {
  _has_bits_[0] |= 0x00000002u;
}
inline void avTCPPacket::clear_has_avpacket() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void avTCPPacket::clear_avpacket() {
  if (avpacket_ != NULL) avpacket_->::proto::base::avPacket::Clear();
  clear_has_avpacket();
}
inline const ::proto::base::avPacket& avTCPPacket::avpacket() const {
  // @@protoc_insertion_point(field_get:proto.base.avTCPPacket.avpacket)
  return avpacket_ != NULL ? *avpacket_ : *default_instance_->avpacket_;
}
inline ::proto::base::avPacket* avTCPPacket::mutable_avpacket() {
  set_has_avpacket();
  if (avpacket_ == NULL) avpacket_ = new ::proto::base::avPacket;
  // @@protoc_insertion_point(field_mutable:proto.base.avTCPPacket.avpacket)
  return avpacket_;
}
inline ::proto::base::avPacket* avTCPPacket::release_avpacket() {
  clear_has_avpacket();
  ::proto::base::avPacket* temp = avpacket_;
  avpacket_ = NULL;
  return temp;
}
inline void avTCPPacket::set_allocated_avpacket(::proto::base::avPacket* avpacket) {
  delete avpacket_;
  avpacket_ = avpacket;
  if (avpacket) {
    set_has_avpacket();
  } else {
    clear_has_avpacket();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avTCPPacket.avpacket)
}

// optional .proto.base.avAddress endpoint_address = 3;
inline bool avTCPPacket::has_endpoint_address() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void avTCPPacket::set_has_endpoint_address() {
  _has_bits_[0] |= 0x00000004u;
}
inline void avTCPPacket::clear_has_endpoint_address() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void avTCPPacket::clear_endpoint_address() {
  if (endpoint_address_ != NULL) endpoint_address_->::proto::base::avAddress::Clear();
  clear_has_endpoint_address();
}
inline const ::proto::base::avAddress& avTCPPacket::endpoint_address() const {
  // @@protoc_insertion_point(field_get:proto.base.avTCPPacket.endpoint_address)
  return endpoint_address_ != NULL ? *endpoint_address_ : *default_instance_->endpoint_address_;
}
inline ::proto::base::avAddress* avTCPPacket::mutable_endpoint_address() {
  set_has_endpoint_address();
  if (endpoint_address_ == NULL) endpoint_address_ = new ::proto::base::avAddress;
  // @@protoc_insertion_point(field_mutable:proto.base.avTCPPacket.endpoint_address)
  return endpoint_address_;
}
inline ::proto::base::avAddress* avTCPPacket::release_endpoint_address() {
  clear_has_endpoint_address();
  ::proto::base::avAddress* temp = endpoint_address_;
  endpoint_address_ = NULL;
  return temp;
}
inline void avTCPPacket::set_allocated_endpoint_address(::proto::base::avAddress* endpoint_address) {
  delete endpoint_address_;
  endpoint_address_ = endpoint_address;
  if (endpoint_address) {
    set_has_endpoint_address();
  } else {
    clear_has_endpoint_address();
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avTCPPacket.endpoint_address)
}

// optional bytes endpoint_cert = 4;
inline bool avTCPPacket::has_endpoint_cert() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void avTCPPacket::set_has_endpoint_cert() {
  _has_bits_[0] |= 0x00000008u;
}
inline void avTCPPacket::clear_has_endpoint_cert() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void avTCPPacket::clear_endpoint_cert() {
  if (endpoint_cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    endpoint_cert_->clear();
  }
  clear_has_endpoint_cert();
}
inline const ::std::string& avTCPPacket::endpoint_cert() const {
  // @@protoc_insertion_point(field_get:proto.base.avTCPPacket.endpoint_cert)
  return *endpoint_cert_;
}
inline void avTCPPacket::set_endpoint_cert(const ::std::string& value) {
  set_has_endpoint_cert();
  if (endpoint_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    endpoint_cert_ = new ::std::string;
  }
  endpoint_cert_->assign(value);
  // @@protoc_insertion_point(field_set:proto.base.avTCPPacket.endpoint_cert)
}
inline void avTCPPacket::set_endpoint_cert(const char* value) {
  set_has_endpoint_cert();
  if (endpoint_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    endpoint_cert_ = new ::std::string;
  }
  endpoint_cert_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.base.avTCPPacket.endpoint_cert)
}
inline void avTCPPacket::set_endpoint_cert(const void* value, size_t size) {
  set_has_endpoint_cert();
  if (endpoint_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    endpoint_cert_ = new ::std::string;
  }
  endpoint_cert_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.base.avTCPPacket.endpoint_cert)
}
inline ::std::string* avTCPPacket::mutable_endpoint_cert() {
  set_has_endpoint_cert();
  if (endpoint_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    endpoint_cert_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.base.avTCPPacket.endpoint_cert)
  return endpoint_cert_;
}
inline ::std::string* avTCPPacket::release_endpoint_cert() {
  clear_has_endpoint_cert();
  if (endpoint_cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = endpoint_cert_;
    endpoint_cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void avTCPPacket::set_allocated_endpoint_cert(::std::string* endpoint_cert) {
  if (endpoint_cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete endpoint_cert_;
  }
  if (endpoint_cert) {
    set_has_endpoint_cert();
    endpoint_cert_ = endpoint_cert;
  } else {
    clear_has_endpoint_cert();
    endpoint_cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.base.avTCPPacket.endpoint_cert)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace base
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_avim_2dbase_2eproto__INCLUDED
